### ISSUE TITLE
Window tests are incomplete

### ISSUE THREAD

**Issue by Orace** [morelinq/MoreLINQ#654]
Actually Window test doesn't cover

 - [x] enumerator disposal (in #655)
 - [x] MoveNext calls after enumerator end (in #655)
 - [x] Returned Window are isolated from each others (see #652) (in #655)
 - [x] Test Window method on known results (in #655)
 - [x] Test WindowLeft method on known results  (in #656)
 - [x] Test WindowRight method on known results (in #656)

**Comment by Orace** [comment]
All those tests are now implemented in #653 but they don't pass because of #652

**Comment by Orace** [comment]
Modification inside window are normal see #652 
The test should be updated accordingly.

**Comment by Orace** [comment]
All those tests are now pass in #655

**Comment by Orace** [comment]
Fixed with #655
